# Generated by Django 4.0.2 on 2022-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_section_articlerelevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sectionTitle',
            field=models.CharField(default='Неопределенный раздел', max_length=256, verbose_name='Название раздела'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(default='Неопределенный раздел', related_name='sections', to='articles.Article'),
        ),
    ]
