# Generated by Django 4.0.2 on 2022-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_section_sectiontitle_alter_section_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(related_name='sections', to='articles.Article'),
        ),
    ]
