# Generated by Django 4.0.2 on 2022-02-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_section_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleRelevance',
        ),
    ]
