# Generated by Django 4.0.2 on 2022-02-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_articlerelevance_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleRelevance',
            new_name='ArticleScope',
        ),
    ]
