# Generated by Django 4.0.2 on 2022-02-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_rename_articlerelevance_articlescope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Scope',
        ),
    ]
