# Generated by Django 4.0.2 on 2022-02-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_section_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
