# Generated by Django 4.0.2 on 2022-02-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_scope_articles_alter_articlescope_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='sectionTitle',
            new_name='scopeTitle',
        ),
    ]
