# Generated by Django 4.0.2 on 2022-02-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_rename_sectiontitle_scope_scopetitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
