# Generated by Django 4.0.2 on 2022-02-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='section',
            new_name='scope',
        ),
    ]
