# Generated by Django 4.0.2 on 2022-02-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_rename_section_articlescope_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='scopeTitle',
        ),
    ]
