# Generated by Django 4.0.2 on 2022-02-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_scope_scopetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='scopeTitle',
            field=models.CharField(default='Раздел', max_length=256, verbose_name='Название раздела'),
            preserve_default=False,
        ),
    ]
