# Generated by Django 4.0.2 on 2022-02-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_remove_scope_scopetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название раздела')),
            ],
        ),
    ]
