# Generated by Django 4.0.2 on 2022-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='scope',
            name='name',
            field=models.CharField(default='Тест', max_length=256, verbose_name='Название раздела'),
            preserve_default=False,
        ),
    ]
