# Generated by Django 4.0.2 on 2022-02-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_delete_tag_scope_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='Tag',
        ),
    ]
