# Generated by Django 4.0.2 on 2022-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_rename_scope_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='tag', to='articles.Article'),
        ),
    ]
