# Generated by Django 4.0.2 on 2022-02-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_alter_articlescope_article_alter_articlescope_scope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleScope',
            new_name='Scope',
        ),
    ]
