# Generated by Django 4.0.2 on 2022-02-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_rename_articlescope_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='scope',
        ),
        migrations.AddField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.tag', verbose_name='Название раздела'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article'),
        ),
    ]
