# Generated by Django 4.0.2 on 2022-02-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_remove_scope_scope_scope_tag_alter_scope_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='ArticleScope',
        ),
    ]
